### ISSUE TITLE
Http and Https

### ISSUE THREAD

**Issue by ghassanmas** [FACN4/lords_of_the_north_w3#48]
https://github.com/FACN4/lords_of_the_north_w3/blob/e0aa0d0e36e051107d350eda18327da70b7ce4ce/js/api.js#L17-L35

You can't send xhr request using http protocol then using https, some browser restrict it, so that all the protocols from a page should be consistent.  

May be this the reason for that #43, when I changed to https for gifs API it worked for me locally.

**Comment by matthall8** [comment]
Hey this should be fixed in the latest commit. Please can you check and close if you agree.
