### ISSUE TITLE
App Architecture 

### ISSUE THREAD

**Issue by ghassanmas** [FACN4/lords_of_the_north_w3#49]
While I have been following the date flow of your app, I noticed that the dom is calling this function: which is in the API file 
```
function getGotApi(key, house) {
  if (house) {
    var url = "https://www.anapioficeandfire.com/api/houses/" + key;
  } else {
    var url = "https://www.anapioficeandfire.com/api/characters/" + key;
  }
  fetch(url, dynamicTextGeneration);
}

```
But then that function is calling fetch and passing a DOM function as a callback, I would suggest making it this way:

```
function getGotApi(key, house) {
  if (house) {
    var url = "https://www.anapioficeandfire.com/api/houses/" + key;
  } else {
    var url = "https://www.anapioficeandfire.com/api/characters/" + key;
  }
  return(url);
}

```
Then in the DOM : 

`fetch(getGotApi(key, house), dynamicTextGeneration)`

**Comment by matthall8** [comment]
Hey this should be fixed in the latest commit. Please can you check and close if you agree.
